package secret

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"go.uber.org/fx"
	"go.uber.org/zap"

	"github.com/dontagr/pandora/internal/server/faultTolerance/pgretry"
	"github.com/dontagr/pandora/internal/server/store/models"
)

const (
	searchSyncSecretSQL      = `SELECT kind, label, sec_data, meta_data, dt, ver FROM public.secret WHERE user_id=$1`
	searchListSecretSQL      = `SELECT label, dt, ver FROM public.secret WHERE user_id=$1 AND kind=$2 ORDER BY id ASC`
	deleteSecretSQL          = `DELETE FROM public.secret WHERE user_id=$1 AND kind=$2 AND label=$3`
	searchLabelSecretSQL     = `SELECT sec_data, meta_data, dt, ver FROM public.secret WHERE user_id=$1 AND kind=$2 AND label=$3`
	searchSecretForUpdateSQL = `SELECT sec_data, meta_data, dt, ver FROM public.secret WHERE user_id=$1 AND kind=$2 AND label=$3 FOR UPDATE`
	insertSecretSQL          = `INSERT INTO public.secret (user_id, kind, label, sec_data, meta_data, dt, ver) VALUES ($1, $2, $3, $4, $5, NOW(), $6) ON CONFLICT (user_id, kind, label) DO UPDATE SET sec_data = excluded.sec_data, meta_data = excluded.meta_data, dt = excluded.dt, ver = excluded.ver;`
	createSecretTable        = `
CREATE TABLE IF NOT EXISTS public."secret" (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id bigint not null,
	kind VARCHAR(10) not null,
	label VARCHAR(255) not null,
	sec_data TEXT not null,
	meta_data TEXT not null,
    dt timestamptz DEFAULT NOW() NOT NULL,
    ver int DEFAULT 1 not null,
	CONSTRAINT user_id_kind_label UNIQUE (user_id,kind,label),
	CONSTRAINT secret_pk PRIMARY KEY ("id")
);
`
)

type Secret struct {
	dbpool *pgretry.PgxRetry
	log    *zap.SugaredLogger
}

func NewSecret(log *zap.SugaredLogger, dbpool *pgretry.PgxRetry, lc fx.Lifecycle) *Secret {
	secret := Secret{
		dbpool: dbpool,
		log:    log,
	}

	lc.Append(fx.Hook{
		OnStart: func(ctx context.Context) error {
			return secret.addShema(ctx)
		},
	})

	return &secret
}

func (s *Secret) addShema(ctx context.Context) error {
	_, err := s.dbpool.Exec(ctx, createSecretTable)

	return err
}

func (s *Secret) DeleteSecret(userId int, kind string, label string) error {
	_, err := s.dbpool.Exec(context.Background(), deleteSecretSQL, userId, kind, label)
	if err != nil {
		return fmt.Errorf("ошибка при удалении секрета: %w", err)
	}

	return nil
}

func (s *Secret) SyncSecret(userId int) (*models.SecretSync, error) {
	rows, err := s.dbpool.Query(context.Background(), searchSyncSecretSQL, userId)
	if err != nil {
		return nil, fmt.Errorf("ошибка при извлечении cекретов: %w", err)
	}
	defer rows.Close()

	result := &models.SecretSync{List: make([]models.Secret, 0)}
	for rows.Next() {
		secret := new(models.Secret)
		err := rows.Scan(&secret.Kind, &secret.Label, &secret.Data, &secret.Meta, &secret.DT, &secret.Version)
		if err != nil {
			return nil, fmt.Errorf("ошибка при сканировании cекретов: %w", err)
		}

		result.List = append(result.List, *secret)
	}

	return result, nil
}

func (s *Secret) GetListSecret(userId int, kind string) (*models.SecretList, error) {
	rows, err := s.dbpool.Query(context.Background(), searchListSecretSQL, userId, kind)
	if err != nil {
		return nil, fmt.Errorf("ошибка при извлечении cекретов: %w", err)
	}
	defer rows.Close()

	result := &models.SecretList{List: make([]models.SecretLite, 0)}
	for rows.Next() {
		secret := new(models.SecretLite)
		err := rows.Scan(&secret.Label, &secret.DT, &secret.Version)
		if err != nil {
			return nil, fmt.Errorf("ошибка при сканировании cекретов: %w", err)
		}

		result.List = append(result.List, *secret)
	}

	return result, nil
}

func (s *Secret) GetSecret(userId int, kind string, label string) (*models.Secret, error) {
	secret := models.Secret{
		Kind:  kind,
		Label: label,
	}
	err := s.dbpool.QueryRow(context.Background(), searchLabelSecretSQL, userId, kind, label).Scan(
		&secret.Data,
		&secret.Meta,
		&secret.DT,
		&secret.Version,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	return &secret, nil
}

func (s *Secret) SaveSecret(userId int, kind string, label string, data string, meta string, version int) (*models.Secret, error) {
	tx, txErr := s.dbpool.Begin(context.Background())
	if txErr != nil {
		s.log.Errorf("ошибка начала транзакции: %v", txErr)
	}
	defer func(txErr *error) {
		if *txErr != nil {
			if rollbackErr := tx.Rollback(context.Background()); rollbackErr != nil {
				s.log.Errorf("ошибка отката транзакции: %v", rollbackErr)
			}
		} else {
			if commitErr := tx.Commit(context.Background()); commitErr != nil {
				s.log.Errorf("ошибка при коммите транзакции: %v", commitErr)
			}
		}
	}(&txErr)

	secret := models.Secret{
		Kind:  kind,
		Label: label,
	}
	err := tx.QueryRow(context.Background(), searchSecretForUpdateSQL, userId, kind, label).Scan(
		&secret.Data,
		&secret.Meta,
		&secret.DT,
		&secret.Version,
	)
	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
		txErr = err
		return nil, fmt.Errorf("ошибка при получении версии: %w", err)
	}
	if err == nil && secret.Version >= version {
		return &secret, nil
	}

	_, err = tx.Exec(context.Background(), insertSecretSQL, userId, kind, label, data, meta, version)
	if err != nil {
		txErr = err
		return nil, fmt.Errorf("ошибка при сохранении секрета: %w", err)
	}

	return nil, nil
}
