package secret

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"go.uber.org/fx"
	"go.uber.org/zap"

	"github.com/dontagr/pandora/internal/server/faultTolerance/pgretry"
	"github.com/dontagr/pandora/internal/server/store/models"
)

const (
	searchSecretSQL      = `SELECT label, sec_data, dt, version FROM public.user WHERE user_id=$1 AND kind=$2`
	searchLabelSecretSQL = `SELECT label, sec_data, dt, version FROM public.user WHERE user_id=$1 AND kind=$2 AND label=$3`
	insertSecretSQL      = `INSERT INTO public.secret (user_id, kind, label, sec_data, dt) VALUES ($1, $2, $3, $4, NOW()) ON CONFLICT (id) DO UPDATE SET sec_data = excluded.sec_data, dt = excluded.dt, version = version +1;`
	createSecretTable    = `
CREATE TABLE IF NOT EXISTS public."secret" (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id bigint not null,
	kind VARCHAR(10) not null,
	label VARCHAR(255) not null,
	sec_data TEXT not null,
    dt timestamptz DEFAULT NOW() NOT NULL,
    version int DEFAULT 1 not null,
	CONSTRAINT user_id_kind_label UNIQUE (user_id,kind,label),
	CONSTRAINT user_pk PRIMARY KEY ("id")
);
`
)

type Secret struct {
	dbpool *pgretry.PgxRetry
	log    *zap.SugaredLogger
}

func NewSecret(log *zap.SugaredLogger, dbpool *pgretry.PgxRetry, lc fx.Lifecycle) *Secret {
	secret := Secret{
		dbpool: dbpool,
		log:    log,
	}

	lc.Append(fx.Hook{
		OnStart: func(ctx context.Context) error {
			return secret.addShema(ctx)
		},
	})

	return &secret
}

func (s *Secret) addShema(ctx context.Context) error {
	_, err := s.dbpool.Exec(ctx, createSecretTable)

	return err
}

func (s *Secret) GetSecret(userId int, kind string) (*models.Secret, error) {
	secret := models.Secret{
		UserId: userId,
		Kind:   kind,
	}
	err := s.dbpool.QueryRow(context.Background(), searchSecretSQL, userId, kind).Scan(
		&secret.Label,
		&secret.Data,
		&secret.DT,
		&secret.Version,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return &secret, nil
	}
	if err != nil {
		return nil, err
	}

	return &secret, nil
}

func (s *Secret) SaveSecret(userId int, kind string, label string, data string) error {
	_, err := s.dbpool.Exec(context.Background(), insertSecretSQL, userId, kind, label, data)
	if err != nil {
		return fmt.Errorf("ошибка при сохранении ctrhtnf: %w", err)
	}

	return nil
}
