package user

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"go.uber.org/fx"
	"go.uber.org/zap"

	"github.com/dontagr/pandora/internal/server/faultTolerance/pgretry"
	"github.com/dontagr/pandora/internal/server/store/models"
)

const (
	searchUserSQL   = `SELECT id, login, password FROM public.user WHERE login=$1`
	insertUserSQL   = `INSERT INTO public.user (login, password) VALUES ($1, $2);`
	createUserTable = `
CREATE TABLE IF NOT EXISTS public."user" (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	login varchar(255) not null,
	password VARCHAR(255) not null,
	CONSTRAINT user_login UNIQUE ("login"),
	CONSTRAINT user_pk PRIMARY KEY ("id")
);
`
)

type User struct {
	dbpool *pgretry.PgxRetry
	log    *zap.SugaredLogger
}

func NewUser(log *zap.SugaredLogger, dbpool *pgretry.PgxRetry, lc fx.Lifecycle) *User {
	user := User{
		dbpool: dbpool,
		log:    log,
	}

	lc.Append(fx.Hook{
		OnStart: func(ctx context.Context) error {
			return user.addShema(ctx)
		},
	})

	return &user
}

func (u *User) addShema(ctx context.Context) error {
	_, err := u.dbpool.Exec(ctx, createUserTable)

	return err
}

func (u *User) GetUser(login string) (*models.User, error) {
	var user models.User
	err := u.dbpool.QueryRow(context.Background(), searchUserSQL, login).Scan(
		&user.ID,
		&user.Login,
		&user.PasswordHash,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return &models.User{}, nil
	}
	if err != nil {
		return nil, err
	}

	return &user, nil
}

func (u *User) SaveUser(login string, passwordHash string) error {
	_, err := u.dbpool.Exec(context.Background(), insertUserSQL, login, passwordHash)
	if err != nil {
		return fmt.Errorf("ошибка при сохранении пользователя: %w", err)
	}

	return nil
}
